import { type Metadata } from "next";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
import { Geist, Geist_Mono } from "next/font/google";
import ThemeToggle from "@/app/components/theme-toggle";
import { ThemeProvider } from "@/app/components/theme-provider";
import "./globals.css";

const THEME_STORAGE_KEY = "sonexa-theme";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Clerk Next.js Quickstart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const themeInitScript = `(function(){try{var stored=localStorage.getItem('${THEME_STORAGE_KEY}');var system=window.matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light';var theme=stored==='dark'||stored==='light'?stored:system;var root=document.documentElement;root.dataset.theme=theme;if(theme==='dark'){root.classList.add('dark');}else{root.classList.remove('dark');}}catch(e){}})();`;

  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <script
            dangerouslySetInnerHTML={{
              __html: themeInitScript,
            }}
          />
          <ThemeProvider>
            <header className="flex h-16 items-center justify-end gap-4 border-b border-(--color-app-border) bg-(--color-app-surface) px-4 text-(--color-app-text)">
              <ThemeToggle />
              <SignedOut>
                <SignInButton />
                <SignUpButton>
                  <button className="rounded-full bg-(--color-app-accent) px-4 py-2 text-sm font-medium text-(--color-app-accent-foreground) shadow-sm transition hover:opacity-90">
                    Sign Up
                  </button>
                </SignUpButton>
              </SignedOut>
              <SignedIn>
                <UserButton />
              </SignedIn>
            </header>
            {children}
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
